apiVersion: v1
kind: Service
metadata:
  name: loyalty-api-service
  namespace: default
  labels:
    app: loyalty-api
spec:
  type: LoadBalancer
  selector:
    app: loyalty-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None
